# Generated by Django 3.2.9 on 2021-11-29 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('neighbourhood', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Cadastro de Informações de Usuário',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('user_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userinfo')),
            ],
            options={
                'verbose_name': 'Cadastro de Usuário',
                'ordering': ['username'],
            },
        ),
    ]
