version: "3.7"
services:
  streamlit:
    build: .
    container_name: streamlit_container
    command: "streamlit run routes.py"
    ports:
      - "8501:8501"
    volumes:
      - "./src:/usr/src/app/src"